### PR TITLE
Fix rendering for InlayHintLabelPart[]

### LINKED ISSUE #31: `rust-analyzer`: type hints joined with `, `
`rust-tools.nvim`'s returning an error for type hints to me, so I've tried to setup this plugin. Here is my config:
```lua
local server_configs = {
    ["clangd"] = {
        --- ....
    },
    ["rust-analyzer"] = {
        imports = {
            granularity = {
                group = "module",
            },
            prefix = "self",
        },
        cargo = {
            buildScripts = {
                enable = true,
            },
        },
        procMacro = {
            enable = true,
        },
        inlayHints = {
            enabled = true,
            typeHints = {
                enable = true,
            },
        },
    },
}
```
Here is my lsp setup & attach event:
```lua
mason_lsp.setup_handlers({
    function(svr)
        lsp_cfg[svr].setup({
            on_attach = function(_, _) end,
            capabilities = capabilities, -- global to `lspserver.protocol.make_client_capabilities()`
            settings = server_configs[svr],
        })
    end,
})

require("lsp-inlayhints").setup()
require("vim").api.nvim_create_augroup("LspAttach_inlayhints", {})
require("vim").api.nvim_create_autocmd("LspAttach", {
    group = "LspAttach_inlayhints",
    callback = function(args)
        if not (args.data and args.data.client_id) then
            return
        end

        local bufnr = args.buf
        local client = require("vim").lsp.get_client_by_id(args.data.client_id)
        require("lsp-inlayhints").on_attach(client, bufnr)
        require("nvim-navic").attach(client, bufnr)
    end,
})
```
The parameter name hints is working, but the type hints seem to handle each token as a different type:

issue

### PR DESCRIPTION
**Pull request by brian14708**
Fixes #31 

Reference: https://github.com/simrat39/rust-tools.nvim/commit/a47f5d61ce06a433998fb5711f723773e3156f46

### CODE REVIEW

**Comment by lvimuser** [comment]
Can you confirm no regressions for other language servers?

File: lua/lsp-inlayhints/handler_helper.lua [hunk 1]
```diff
@@ -56,9 +56,11 @@ local fill_labels = function(line_hints)
     -- label may be a string or InlayHintLabelPart[]
     -- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHintLabelPart
     if type(hint.label) == "table" then
+      local parts = ''
       for _, label_part in ipairs(hint.label) do
-        table.insert(tbl, label_part.value)
+        parts = parts .. label_part.value
       end
+      table.insert(tbl, parts)
```
Comment (lvimuser) [inline lua/lsp-inlayhints/handler_helper.lua:63]:
```suggestion
      local parts = {}
      for _, label_part in ipairs(hint.label) do
        parts[#parts + 1] = label_part.value
      end
      table.insert(tbl, table.concat(parts))
```

**Review by lvimuser — CHANGES_REQUESTED** [review]

**Review by lvimuser — APPROVED** [review]

**Comment by brian14708** [comment]
> Can you confirm no regressions for other language servers?

I've tested using `gopls` and `clangd`, haven't seen any regression problems.
